name: co-challenge

channels:
    - conda-forge

dependencies:

    # conda dependencies
    # Use single '=' signs!

    # core packages
    - python=3.7
    - pip=21.0.1

    # geo packages
    - rasterio=1.1.5
    - gdal=3.0.4
